name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Install Rocq
        uses: tchajed/setup-rocq@v1
      - name: Install dependencies
        run: |
          opam pin add --no-action .
          opam install --deps-only .
      - name: Rocq build
        run: make -j4
      - name: opam install
        run: opam install --assume-built .
      - name: opam uninstall
        run: opam uninstall .

  check-goose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: check goose output
        run: |
          git clone --depth=1 https://github.com/mit-pdos/tulip ~/tulip
          ./etc/update-goose.sh ~/tulip
          git diff --exit-code
